import sqlite3
import os
from datetime import datetime
import hashlib

from langchain_chroma import Chroma
from langchain_community.embeddings import OllamaEmbeddings
from langchain_community.llms import Ollama

DB_FOLDER = "facts_db"
DB_PATH = os.path.join(DB_FOLDER, "facts_history.db")
SCHEMA_PATH = os.path.join(DB_FOLDER, "schema.sql")


VDB_DIR = "chroma_db"
MODEL_NAME = "llama3.2:latest"
embeddings = OllamaEmbeddings(model=MODEL_NAME)
vector_db = Chroma(persist_directory=VDB_DIR, embedding_function=embeddings)
llm = Ollama(model=MODEL_NAME)


def init_db():
    """Initializes the database using the external SQL schema file."""
    if not os.path.exists(DB_FOLDER):
        os.makedirs(DB_FOLDER)
    
    # Connect to SQLite
    conn = sqlite3.connect(DB_PATH)
    
    try:
        # Read the SQL file
        with open(SCHEMA_PATH, 'r') as f:
            sql_schema = f.read()
        
        # Execute the full schema (multiple statements)
        conn.executescript(sql_schema)
        conn.commit()
        print("✅ Database schema applied from SQL file.")
        
    except FileNotFoundError:
        print(f"❌ Error: {SCHEMA_PATH} not found. Create it first!")
    except sqlite3.Error as e:
        print(f"❌ SQL Error: {e}")
    finally:
        conn.close()


def is_file_ingested(filename):
    """Checks if the PDF is already in ChromaDB."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('SELECT 1 FROM ingested_files WHERE filename = ?', (filename,))
    result = cursor.fetchone()
    conn.close()
    return result is not None


def mark_as_ingested(filename, total_chunks=0):
    """Records that a PDF has been processed."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('INSERT OR REPLACE INTO ingested_files (filename, total_chunks, ingested_at) VALUES (?, ?, ?)', 
                   (filename, total_chunks, datetime.now()))
    conn.commit()
    conn.close()


def is_already_sent(fact_hash):
    """Checks if the hash exists in the SQLite table."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # It looks for the unique fingerprint (hash) in the 'facts' table
    cursor.execute('SELECT 1 FROM facts WHERE hash = ?', (fact_hash,))
    result = cursor.fetchone()
    
    conn.close()
    
    # Returns True if found, False if it's a new discovery
    return result is not None


def get_recent_facts(limit=15):
    """
    Retrieves the text of the most recently sent facts.
    Used by the Archivist Agent to prevent semantic repetition.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    try:
        # We only need the text of the fact for the LLM to compare
        cursor.execute('''
            SELECT fact_text FROM facts 
            ORDER BY created_at DESC 
            LIMIT ?
        ''', (limit,))
        
        # Flatten the list of tuples into a simple list of strings
        recent_facts = [row[0] for row in cursor.fetchall()]
        return recent_facts
    except sqlite3.Error as e:
        print(f"❌ Database error in get_recent_facts: {e}")
        return []
    finally:
        conn.close()


def save_fact(fact_text, fact_hash, file_id=None):
    """Saves a new discovery and returns its unique fact_id."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    new_id = None
    
    try:
        cursor.execute('''
            INSERT INTO facts (hash, fact_text, file_id, user_feedback, created_at) 
            VALUES (?, ?, ?, ?, ?)
        ''', (fact_hash, fact_text, file_id, 0, datetime.now()))
        
        conn.commit()
        # This gets the ID that was just generated by AUTOINCREMENT
        new_id = cursor.lastrowid 
        
    except sqlite3.IntegrityError:
        print("--- Duplicate hash detected during save ---")
    finally:
        conn.close()
    
    return new_id


def log_user_feedback(fact_hash, score):
    """
    Updates the feedback for a specific fact.
    score: 1 (Like), -1 (Dislike)
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('UPDATE facts SET user_feedback = ? WHERE hash = ?', (score, fact_hash))
    conn.commit()
    conn.close()
    print(f"Feedback {score} recorded for {fact_hash[:8]}")


def update_feedback(fact_id, score):
    """Updates the user_feedback column (1 for Like, -1 for Dislike)."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('UPDATE facts SET user_feedback = ? WHERE fact_id = ?', (score, fact_id))
    conn.commit()
    conn.close()


def get_existing_fact_id(fact_hash):
    """
    Checks if a fact exists by hash.
    Returns the fact_id if found, otherwise None.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # We select the new Integer ID instead of just '1'
    cursor.execute('SELECT fact_id FROM facts WHERE hash = ?', (fact_hash,))
    result = cursor.fetchone()
    conn.close()
    
    return result[0] if result else None


def get_file_id(filename):
    """Retrieves the auto-increment ID for a given filename."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('SELECT file_id FROM ingested_files WHERE filename = ?', (filename,))
    result = cursor.fetchone()
    conn.close()
    return result[0] if result else None


def truncate_ingested_files():
    """Records that a PDF has been processed."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('DELETE FROM ingested_files;')
    conn.commit()
    conn.close()


def truncate_facts():
    """Records that a PDF has been processed."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('DELETE FROM facts;')
    conn.commit()
    conn.close()


def get_recent_file_ids(hours=48):
    """Returns a list of file_ids that provided facts recently."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # We pass the full interval string to the placeholder
    interval = f"-{hours} hours"
    
    try:
        cursor.execute("""
            SELECT DISTINCT file_id FROM facts 
            WHERE created_at > datetime('now', ?)
        """, (interval,))
        
        recent_ids = [row[0] for row in cursor.fetchall()]
        return recent_ids
    except sqlite3.Error as e:
        print(f"❌ SQL Error in get_recent_file_ids: {e}")
        return []
    finally:
        conn.close()


def get_book_weights():
    """Returns a dictionary of {file_id: weight} based on likes."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Base weight for every book is 1
    cursor.execute("SELECT file_id FROM ingested_files")
    weights = {row[0]: 1.0 for row in cursor.fetchall()}
    
    # Add 0.5 weight for every 'Like' (up to a max cap of 5.0 to avoid monopoly)
    cursor.execute("""
        SELECT file_id, COUNT(*) as likes 
        FROM facts 
        WHERE user_feedback = 1 
        GROUP BY file_id
    """)
    
    for file_id, likes in cursor.fetchall():
        # Formula: 1.0 + (likes * 0.5), maxed at 5.0
        weights[file_id] = min(5.0, 1.0 + (likes * 0.5))
        
    conn.close()
    return weights


if __name__ == "__main__":
    init_db()