import sqlite3
import os
from datetime import datetime
import hashlib

DB_FOLDER = "facts_db"
DB_PATH = os.path.join(DB_FOLDER, "facts_history.db")
SCHEMA_PATH = os.path.join(DB_FOLDER, "schema.sql")

def init_db():
    """Initializes the database using the external SQL schema file."""
    if not os.path.exists(DB_FOLDER):
        os.makedirs(DB_FOLDER)
    
    # Connect to SQLite
    conn = sqlite3.connect(DB_PATH)
    
    try:
        # Read the SQL file
        with open(SCHEMA_PATH, 'r') as f:
            sql_schema = f.read()
        
        # Execute the full schema (multiple statements)
        conn.executescript(sql_schema)
        conn.commit()
        print("✅ Database schema applied from SQL file.")
        
    except FileNotFoundError:
        print(f"❌ Error: {SCHEMA_PATH} not found. Create it first!")
    except sqlite3.Error as e:
        print(f"❌ SQL Error: {e}")
    finally:
        conn.close()


def is_file_ingested(filename):
    """Checks if the PDF is already in ChromaDB."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('SELECT 1 FROM ingested_files WHERE filename = ?', (filename,))
    result = cursor.fetchone()
    conn.close()
    return result is not None


def mark_as_ingested(filename, total_chunks=0):
    """Records that a PDF has been processed."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('INSERT OR REPLACE INTO ingested_files (filename, total_chunks, ingested_at) VALUES (?, ?, ?)', 
                   (filename, total_chunks, datetime.now()))
    conn.commit()
    conn.close()


def is_already_sent(fact_hash):
    """Checks if the hash exists in the SQLite table."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # It looks for the unique fingerprint (hash) in the 'facts' table
    cursor.execute('SELECT 1 FROM facts WHERE hash = ?', (fact_hash,))
    result = cursor.fetchone()
    
    conn.close()
    
    # Returns True if found, False if it's a new discovery
    return result is not None


def save_fact(fact_text, fact_hash, file_id=None):
    """Saves a new discovery and returns its unique fact_id."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    new_id = None
    
    try:
        cursor.execute('''
            INSERT INTO facts (hash, fact_text, file_id, user_feedback, created_at) 
            VALUES (?, ?, ?, ?, ?)
        ''', (fact_hash, fact_text, file_id, 0, datetime.now()))
        
        conn.commit()
        # This gets the ID that was just generated by AUTOINCREMENT
        new_id = cursor.lastrowid 
        
    except sqlite3.IntegrityError:
        print("--- Duplicate hash detected during save ---")
    finally:
        conn.close()
    
    return new_id


def log_user_feedback(fact_hash, score):
    """
    Updates the feedback for a specific fact.
    score: 1 (Like), -1 (Dislike)
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('UPDATE facts SET user_feedback = ? WHERE hash = ?', (score, fact_hash))
    conn.commit()
    conn.close()
    print(f"Feedback {score} recorded for {fact_hash[:8]}")


def update_feedback(fact_hash, score):
    """Updates the user_feedback column (1 for Like, -1 for Dislike)."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('UPDATE facts SET user_feedback = ? WHERE hash = ?', (score, fact_hash))
    conn.commit()
    conn.close()


def get_existing_fact_id(fact_hash):
    """
    Checks if a fact exists by hash.
    Returns the fact_id if found, otherwise None.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # We select the new Integer ID instead of just '1'
    cursor.execute('SELECT fact_id FROM facts WHERE hash = ?', (fact_hash,))
    result = cursor.fetchone()
    conn.close()
    
    return result[0] if result else None


def get_file_id(filename):
    """Retrieves the auto-increment ID for a given filename."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('SELECT file_id FROM ingested_files WHERE filename = ?', (filename,))
    result = cursor.fetchone()
    conn.close()
    return result[0] if result else None


def truncate_table():
    """Records that a PDF has been processed."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('DELETE FROM ingested_files;')
    conn.commit()
    conn.close()


def truncate_facts():
    """Records that a PDF has been processed."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute('DELETE FROM facts;')
    conn.commit()
    conn.close()


if __name__ == "__main__":
    init_db()